### ISSUE TITLE
编译sass文件出错

### ISSUE THREAD

**Issue by SeptemberMaples** [DDFE/miniapps#1]
使用 miniapp build 时，*.sass文件编译成 *.wxss后，.wxss文件出错，显示 [object Object]。
是我打开方式不对么~~

**Comment by zhangyaochun** [comment]
贴个图我们看一下呗~

**Comment by SeptemberMaples** [comment]
<img width="690" alt="qq20170111-1 2x" src="https://cloud.githubusercontent.com/assets/4352453/21830776/14d78008-d7da-11e6-9cb1-1560bd7d395f.png">
<img width="545" alt="qq20170111-0 2x" src="https://cloud.githubusercontent.com/assets/4352453/21830779/173f9218-d7da-11e6-8df9-c412cfb7ece2.png">
@zhangyaochun

**Comment by isClumsyBird** [comment]
+1   
不知道能不能生成scss的文件  每次生成都要手动改成scss

**Comment by zhangyaochun** [comment]
升级一下呗，各位亲

**Comment by zhangyaochun** [comment]
sass 项目后缀统一为 

> .scss
